"""Postgres ledger adapter; local SQLite continues to work unchanged.

Keep SQL parameters separate from text. Only SQL authored by this app is adapted.
Each context is one transaction, including bulk import and match operations.
"""
import re
import sqlite3


class Row(dict):
    def __getitem__(self, key):
        return list(self.values())[key] if isinstance(key, int) else super().__getitem__(key)


class Result:
    def __init__(self, cursor, lastrowid=None, rows=None):
        self.cursor = cursor
        self.lastrowid = lastrowid
        self.rows = rows
        self.rowcount = cursor.rowcount if cursor else len(rows or [])

    def fetchall(self):
        if self.rows is not None:
            result, self.rows = self.rows, []
            return result
        return self.cursor.fetchall()

    def fetchone(self):
        if self.rows is not None:
            return self.rows.pop(0) if self.rows else None
        return self.cursor.fetchone()

    def __iter__(self):
        return iter(self.fetchall())


def adapt(sql):
    # Quoted strings stay byte-for-byte intact; ? parameters are outside them.
    parts = re.split("('(?:''|[^'])*')", sql)
    for i in range(0, len(parts), 2):
        parts[i] = re.sub(r'\bend\b', '"end"', parts[i], flags=re.I)
        parts[i] = parts[i].replace('?', '%s')
    sql = ''.join(parts).strip().rstrip(';')
    sql = sql.replace('julianday(m.date)-julianday(%s)', '(m.date::date - %s::date)')
    ignore = bool(re.match(r'INSERT OR IGNORE\b', sql, re.I))
    sql = re.sub(r'^INSERT OR IGNORE\b', 'INSERT', sql, flags=re.I)
    sql = re.sub(r'\bid INTEGER PRIMARY KEY\b', 'id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', sql)
    sql = sql.replace('DEFAULT CURRENT_TIMESTAMP', 'DEFAULT (CURRENT_TIMESTAMP::text)')
    if ignore:
        sql += ' ON CONFLICT DO NOTHING'
    return sql


class Database:
    def __init__(self, url, schema='budget_lpc'):
        import psycopg
        from psycopg import sql
        if not re.fullmatch(r'budget_lpc(?:_test_[a-z0-9]+)?', schema):
            raise ValueError('Invalid Budget LPC schema')
        def row_factory(cursor):
            names = [col.name for col in cursor.description] if cursor.description else []
            return lambda values: Row(zip(names, values))
        self.connection = psycopg.connect(url, connect_timeout=15, row_factory=row_factory, prepare_threshold=None)
        self.connection.execute('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ')
        self.connection.execute(sql.SQL('SET LOCAL search_path TO {}, pg_catalog').format(sql.Identifier(schema)))
        self.schema = schema

    def execute(self, query, params=()):
        import psycopg
        if query.strip().upper() == 'BEGIN IMMEDIATE':
            # Serialize imports before checking fingerprints, like SQLite's
            # write lock. The connection already owns a transaction.
            return Result(self.connection.execute('LOCK TABLE transactions, bank_keys, batches IN SHARE ROW EXCLUSIVE MODE'))
        if query.startswith('PRAGMA table_info('):
            table = query[len('PRAGMA table_info('):-1]
            cursor = self.connection.execute('SELECT ordinal_position AS cid,column_name AS name FROM information_schema.columns WHERE table_schema=%s AND table_name=%s ORDER BY ordinal_position', (self.schema, table))
            return Result(cursor)
        query = adapt(query)
        returns_id = bool(re.match(r'INSERT INTO (accounts|categories|batches|transactions)\b', query, re.I))
        if returns_id:
            query += ' RETURNING id'
        try:
            cursor = self.connection.execute(query, tuple(int(v) if isinstance(v, bool) else v for v in params))
        except psycopg.IntegrityError as exc:
            raise sqlite3.IntegrityError(str(exc)) from exc
        result = Result(cursor)
        if returns_id:
            row = cursor.fetchone()
            result.lastrowid = row[0] if row else None
        return result

    def executescript(self, script):
        # Hosted schemas are installed by migration, never by the web role.
        for table in re.findall(r'CREATE TABLE IF NOT EXISTS (\w+)', script):
            exists = self.connection.execute('SELECT to_regclass(%s)', (self.schema + '.' + table,)).fetchone()[0]
            if not exists:
                raise RuntimeError('Budget LPC database migration is missing: ' + table)

    def backup(self, target):
        # Produce a portable, consistent SQLite backup of ledger tables only.
        tables = ['accounts','categories','batches','transactions','bank_keys','budgets','meta']
        for table in tables:
            columns = self.connection.execute('SELECT column_name,data_type FROM information_schema.columns WHERE table_schema=%s AND table_name=%s ORDER BY ordinal_position', (self.schema, table)).fetchall()
            definitions = ','.join('"'+c['column_name']+'" '+('INTEGER' if c['data_type'] in ('bigint','integer') else 'TEXT') for c in columns)
            target.execute(f'CREATE TABLE "{table}" ({definitions})')
            rows = self.execute(f'SELECT * FROM {table}').fetchall()
            target.executemany(f'INSERT INTO "{table}" VALUES ({",".join("?" for _ in columns)})', [tuple(row.values()) for row in rows])
        target.commit()

    def commit(self):
        self.connection.commit()

    def rollback(self):
        self.connection.rollback()

    def close(self):
        self.connection.close()

