import {useEffect,useRef,useState,type FormEvent,type ReactNode} from 'react';
import {LayoutDashboard,ArrowDownLeft,ArrowUpRight,ArrowRight,Wallet,ReceiptText,Target,CheckCheck,Tags,Settings as SettingsIcon,Upload,Plus,X,Download,ShieldCheck,FileSpreadsheet,Landmark,TrendingUp,ChevronRight,Check} from 'lucide-react';
import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,Legend,ReferenceLine} from 'recharts';
import {api,money,today,type Settings,type Dashboard,type Transaction,type Budget,type Category} from './types';
import ImportWizard from './ImportWizard';
import Ledger from './Ledger';
import InstallApp from './InstallApp';
import {SessionButton} from './AuthGate';

const navigation=[['Dashboard',LayoutDashboard],['Income',Wallet],['Transactions',ReceiptText],['Investments',TrendingUp],['Budget',Target],['Review',CheckCheck],['Categories',Tags],['Settings',SettingsIcon]] as const;
const descriptions:Record<string,string>={Dashboard:'A clearer view of what comes in, goes out, and stays with you.',Income:'Record money received. Match it to bank deposits later.',Transactions:'Every movement, with its original source and your final classification.',Investments:'Contributions tracked separately from everyday spending.',Budget:'Give your money a plan. Then see how the month is going.',Review:'Check imported transactions before they enter your totals.',Categories:'Organize spending in a way that makes sense to you.',Settings:'Your accounts, statement history, and saved data.'};

function Dialog({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const el=ref.current;el?.showModal();return()=>el?.close()},[]);
 return <dialog ref={ref} className={wide?'wide':''} onCancel={e=>{e.preventDefault();onClose()}}><div className="dialog-header"><div><span className="eyebrow">BUDGET LPC</span><h2>{title}</h2></div><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={20}/></button></div>{children}</dialog>
}

export default function App(){
 const [view,setView]=useState('Dashboard');const [month,setMonth]=useState(today().slice(0,7));const [currency,setCurrency]=useState('EUR');const [settings,setSettings]=useState<Settings|null>(null);const [dashboard,setDashboard]=useState<Dashboard|null>(null);const [revision,setRevision]=useState(0);const [toast,setToast]=useState('');const [error,setError]=useState('');const [modal,setModal]=useState<'import'|'entry'|'account'|null>(null);const [edit,setEdit]=useState<Transaction|null>(null);const [initialKind,setInitialKind]=useState('expense');const [returnImport,setReturnImport]=useState(false);
 useEffect(()=>{let active=true;api<Settings>('/api/settings').then(data=>{if(active)setSettings(data)}).catch(e=>active&&setError(e.message));return()=>{active=false}},[revision]);
 useEffect(()=>{let active=true;api<Dashboard>(`/api/dashboard?month=${month}&currency=${currency}`).then(data=>{if(active){setDashboard(data);setError('')}}).catch(e=>active&&setError(e.message));return()=>{active=false}},[month,currency,revision]);
 useEffect(()=>{if(toast){const timer=setTimeout(()=>setToast(''),6500);return()=>clearTimeout(timer)}},[toast]);
 function changed(message:string){setToast(message);setRevision(n=>n+1)}
 function add(kind:string){setEdit(null);setInitialKind(kind);setModal('entry')}
 return <div className="shell">
  <aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setView('Dashboard')}}><img src="/logo-lpc.svg" alt="LPC"/><span>Budget <b>LPC</b><small>PERSONAL FINANCE</small></span></a><div className="nav-label">YOUR WORKSPACE</div><nav aria-label="Main navigation">{navigation.map(([name,Icon])=><button key={name} aria-label={name} title={name} className={view===name?'active':''} aria-current={view===name?'page':undefined} onClick={()=>setView(name)}><Icon size={19}/><span>{name}</span>{name==='Review'&&Boolean(dashboard?.all_pending)&&<em>{dashboard?.all_pending}</em>}</button>)}</nav><div className="sidebar-bottom"><ShieldCheck size={20}/><strong>Made for your money.</strong><p>{settings?.hosted?'Private hosted workspace.':'Stored on this computer.'}<br/>AI only when you ask.</p><div className="sidebar-profile"><span>P</span><div>Personal workspace<small>{settings?.hosted?'Private':'Local'} · Budget LPC</small></div></div></div></aside>
  <main><div className="topline"><span>PERSONAL FINANCE / {view.toUpperCase()}</span><span className="local-dot">{settings?.hosted?'Private workspace':'Local workspace'}</span><SessionButton/></div><header><div><h1>{view==='Dashboard'?'Your financial picture':view}</h1><p>{descriptions[view]}</p></div><div className="header-buttons"><button className="secondary" onClick={()=>setModal('import')}><Upload size={16}/>Import statement</button><button className="primary" onClick={()=>add(view==='Income'?'income':view==='Investments'?'investment':'expense')}><Plus size={16}/>{view==='Income'?'Add income':view==='Investments'?'Add investment':'Add entry'}</button></div></header>
  <div className="period-bar"><div className="period-controls"><label>Month<input aria-label="Selected month" type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value)}}/></label><label>Currency<select aria-label="Selected currency" value={currency} onChange={e=>setCurrency(e.target.value)}>{(settings?.currencies||['EUR']).map(c=><option key={c}>{c}</option>)}</select></label></div><span>One currency at a time. No estimated exchange rates.</span></div>
  {error&&<div role="alert" className="notice error">{error}<button className="text-button" onClick={()=>setRevision(n=>n+1)}>Retry</button></div>}
  {!settings||!dashboard?<div className="empty">Loading your workspace…</div>:<>
   {view==='Dashboard'&&<Overview data={dashboard} onView={setView} onMonth={setMonth} onImport={()=>setModal('import')} latest={settings.latest_month}/>}
   {['Income','Transactions','Investments','Review'].includes(view)&&<Ledger key={view} settings={settings} month={month} currency={currency} view={view} revision={revision} onChange={changed} onEdit={row=>{setEdit(row);setInitialKind(row.kind);setModal('entry')}}/>}
   {view==='Budget'&&<BudgetPage settings={settings} month={month} currency={currency} dashboard={dashboard} revision={revision} onChange={changed}/>}
   {view==='Categories'&&<Categories settings={settings} onChange={changed}/>}
   {view==='Settings'&&<SettingsPage settings={settings} revision={revision} onAccount={()=>{setReturnImport(false);setModal('account')}}/>}
  </>}
  <footer><span>Budget LPC</span><span>Clarity today. More room tomorrow.</span></footer></main>
  {toast&&<div role="status" className="toast"><Check size={18}/>{toast}<button className="icon-button" onClick={()=>setToast('')} aria-label="Dismiss message"><X size={15}/></button></div>}
  {modal==='import'&&settings&&<Dialog title="Import a bank statement" wide onClose={()=>setModal(null)}><ImportWizard settings={settings} onAccount={()=>{setReturnImport(true);setModal('account')}} onDone={message=>{setModal(null);setView('Review');changed(message)}}/></Dialog>}
  {modal==='entry'&&settings&&<Dialog title={edit?'Edit entry':initialKind==='income'?'Add income':'Add a transaction'} onClose={()=>setModal(null)}><EntryForm settings={settings} currency={currency} kind={initialKind} entry={edit} onSave={message=>{setModal(null);changed(message)}}/></Dialog>}
  {modal==='account'&&settings&&<Dialog title="Add a bank account" onClose={()=>setModal(returnImport?'import':null)}><AccountForm settings={settings} currency={currency} onSave={()=>{changed('Account added. You can now import statements for it.');setModal(returnImport?'import':null)}}/></Dialog>}
 </div>
}

function Overview({data,onView,onMonth,onImport,latest}:{data:Dashboard;onView:(v:string)=>void;onMonth:(m:string)=>void;onImport:()=>void;latest:string|null}){
 const t=data.totals;const max=Math.max(1,...data.categories.map(c=>Math.abs(c.cents)));const monthName=new Date(data.month+'-02').toLocaleDateString('en-GB',{month:'long',year:'numeric'});
 const cards=[{label:'Income received',value:t.income,icon:ArrowDownLeft,note:'Approved money in',className:'income'},{label:'Net expenses',value:t.expenses,icon:ArrowUpRight,note:'Spending less refunds',className:'expense'},{label:'Net savings',value:t.savings,icon:Wallet,note:'Income − net expenses',className:'savings'}];
 return <>
  {data.pending>0&&<button className="pending-banner" onClick={()=>onView('Review')}><CheckCheck size={20}/><span><strong>{data.pending} transactions await your review this month.</strong> Totals below include approved entries only.</span><ArrowRight size={18}/></button>}
  <div className="kpi-grid">{cards.map(c=><article className={'kpi '+c.className} key={c.label}><div><span>{c.label}</span><c.icon size={19}/></div><strong>{money(c.value,data.currency)}</strong><small>{c.note}</small></article>)}<article className="kpi rate"><div><span>Savings rate</span><TrendingUp size={19}/></div><strong>{t.savings_rate===null?'—':`${t.savings_rate.toFixed(1)}%`}</strong><small>{t.savings_rate===null?'Add income to calculate':`${monthName} · approved entries`}</small></article></div>
  <section className="panel chart-panel"><div className="panel-heading"><div><span className="eyebrow">THE BIG PICTURE</span><h2>Income, spending & savings</h2></div><span className="subtle-tag">{data.month.slice(0,4)} · {data.currency}</span></div><div className="main-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.monthly} barGap={3} margin={{top:15,right:10,bottom:0,left:5}} onClick={(state:any)=>{const row=state?.activePayload?.[0]?.payload;if(row?.month)onMonth(row.month)}}><CartesianGrid vertical={false} stroke="#e8e8e0"/><XAxis dataKey="month" tickFormatter={v=>new Date(v+'-02').toLocaleDateString('en-GB',{month:'short'})} axisLine={false} tickLine={false} tick={{fontSize:11,fill:'#80867f'}}/><YAxis tickFormatter={v=>new Intl.NumberFormat('en',{notation:'compact'}).format(v)} axisLine={false} tickLine={false} tick={{fontSize:11,fill:'#80867f'}}/><Tooltip formatter={(value:any,name:any)=>[money(Number(value)*100,data.currency),name]} labelFormatter={v=>String(v)} contentStyle={{border:'1px solid #ddd',borderRadius:9,fontSize:12}}/><Legend iconType="circle" iconSize={8} wrapperStyle={{fontSize:12,paddingTop:15}}/><ReferenceLine y={0} stroke="#d5d8cd"/><Bar name="Income" dataKey="income" fill="#537d70" radius={[3,3,0,0]}/><Bar name="Expenses" dataKey="expenses" fill="#c4a67e" radius={[3,3,0,0]}/><Bar name="Savings" dataKey="savings" fill="#bacbb8" radius={[3,3,0,0]}/></BarChart></ResponsiveContainer></div></section>
  {!data.recent.length&&<div className="empty-month"><div><h3>A fresh page for {monthName}.</h3><p>Add income or import a bank statement to fill in your financial picture.</p></div>{latest&&latest!==data.month?<button className="secondary" onClick={()=>onMonth(latest)}>View latest recorded month <ArrowRight size={16}/></button>:<button className="secondary" onClick={onImport}>Import statement <ArrowRight size={16}/></button>}</div>}
  <div className="dashboard-bottom"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">WHERE IT GOES</span><h2>Spending by category</h2></div><button className="text-button" onClick={()=>onView('Transactions')}>View all <ChevronRight size={14}/></button></div>{data.categories.length?<div className="category-breakdown">{data.categories.map(c=><div key={c.id??'none'}><div><span><i style={{background:c.color}}/>{c.name}</span><strong>{money(c.cents,data.currency)}</strong></div><div className="track"><span style={{width:`${Math.abs(c.cents)/max*100}%`,background:c.cents<0?'#729d91':c.color}}/></div></div>)}</div>:<p className="empty-small">Your reviewed expenses will appear here.</p>}</section>
  <section className="panel money-plan"><span className="eyebrow">ROOM TO MOVE</span><h2>After everyday spending</h2><div className="plan-line"><span>Net savings</span><strong>{money(t.savings,data.currency)}</strong></div><div className="plan-line"><span>Investment contributions</span><strong>{money(t.investments,data.currency)}</strong></div><div className="available"><span>Remaining after investments</span><strong>{money(t.after_investments,data.currency)}</strong></div><div className="expense-split"><span>Fixed <b>{money(t.fixed,data.currency)}</b></span><span>Variable <b>{money(t.variable,data.currency)}</b></span></div><button className="secondary" onClick={()=>onView('Budget')}>Review monthly plan <ArrowRight size={16}/></button></section></div>
  <section className="panel recent-panel"><div className="panel-heading"><div><span className="eyebrow">LATEST ACTIVITY</span><h2>Recent transactions</h2></div><button className="text-button" onClick={()=>onView('Transactions')}>All transactions <ArrowRight size={15}/></button></div>{data.recent.length?<div className="table-scroll"><table><thead><tr><th>Transaction</th><th>Date</th><th>Category / type</th><th className="number">Amount</th></tr></thead><tbody>{data.recent.map(r=><tr key={r.id}><td><strong>{r.description}</strong><small>{r.account}</small></td><td>{r.date}</td><td><span className="badge neutral">{r.category||r.kind}</span></td><td className={`number ${r.cents>=0?'positive':''}`}>{money(r.cents,r.currency)}</td></tr>)}</tbody></table></div>:<p className="empty-small">No approved activity in this month and currency.</p>}</section>
 </>
}

function EntryForm({settings,currency,kind,entry,onSave}:{settings:Settings;currency:string;kind:string;entry:Transaction|null;onSave:(message:string)=>void}){
 const [type,setType]=useState(entry?.kind||kind);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=new FormData(event.currentTarget);const body=Object.fromEntries(form);try{await api(entry?`/api/transactions/${entry.id}`:'/api/transactions',{method:entry?'PUT':'POST',body:JSON.stringify({...body,category_id:body.category_id?Number(body.category_id):null,account_id:Number(body.account_id)})});onSave(entry?'Entry updated.':'Entry saved. Your dashboard is up to date.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <form onSubmit={submit}><p className="muted form-intro">Enter the amount you received or spent. Bank imports can be matched to this entry later.</p><div className="form-grid"><label>Type<select name="kind" value={type} onChange={e=>setType(e.target.value)}>{['income','expense','refund','transfer','investment'].map(k=><option key={k}>{k}</option>)}</select></label><label>Date<input name="date" type="date" required defaultValue={entry?.date||today()}/></label><label className="full">Description<input name="description" required maxLength={500} placeholder={type==='income'?'e.g. Monthly salary':'What was this for?'} defaultValue={entry?.description}/></label><label>Amount<input name="amount" type="number" step="0.01" min={type==='transfer'?undefined:'0.01'} required defaultValue={entry?(type==='transfer'?entry.cents:Math.abs(entry.cents))/100:undefined}/></label><label>Currency<select name="currency" defaultValue={entry?.currency||currency}>{settings.currencies.map(c=><option key={c}>{c}</option>)}</select></label><label>Account<select name="account_id" defaultValue={entry?.account_id||settings.accounts[0]?.id}>{settings.accounts.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label><label>Category<select name="category_id" defaultValue={entry?.category_id||''}><option value="">Uncategorized</option>{settings.categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Expense pattern<select name="expense_type" defaultValue={entry?.expense_type||'variable'}><option value="variable">Variable</option><option value="fixed">Fixed</option></select></label><label>Label<input name="label" maxLength={80} defaultValue={entry?.label} placeholder="Optional"/></label><label className="full">Notes<textarea name="notes" maxLength={2000} defaultValue={entry?.notes} rows={2}/></label></div>{type==='transfer'&&<p className="muted">For transfers, use a negative amount for money out and positive for money in. Transfers do not affect income or spending totals.</p>}{error&&<p role="alert" className="error-text">{error}</p>}<div className="dialog-actions"><button className="primary" disabled={busy}>{busy?'Saving…':'Save entry'}<Check size={16}/></button></div></form>
}

function AccountForm({settings,currency,onSave}:{settings:Settings;currency:string;onSave:()=>void}){
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{await api('/api/accounts',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});onSave()}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
 return <form onSubmit={submit}><p className="muted form-intro">Give each real account its own name. Duplicate checks apply within that account. You do not need to enter an account number or login.</p><div className="form-grid"><label className="full">Account name<input name="name" required maxLength={100} placeholder="e.g. ADCB current account"/></label><label>Bank<input name="bank" maxLength={80} list="banks" placeholder="Choose or type a bank"/><datalist id="banks">{['ING','CaixaBank','ADCB','Revolut','Seychelles bank','Other'].map(b=><option key={b}>{b}</option>)}</datalist></label><label>Default currency<select name="currency" defaultValue={currency}>{settings.currencies.map(c=><option key={c}>{c}</option>)}</select></label></div><p className="muted">For a multi-currency Revolut statement, a currency column overrides this default. Each currency keeps its own totals.</p>{error&&<p role="alert" className="error-text">{error}</p>}<div className="dialog-actions"><button className="primary" disabled={busy}>{busy?'Saving…':'Create account'}</button></div></form>
}

function BudgetPage({settings,month,currency,dashboard,revision,onChange}:{settings:Settings;month:string;currency:string;dashboard:Dashboard;revision:number;onChange:(s:string)=>void}){
 const [budget,setBudget]=useState<Budget|null>(null);const [income,setIncome]=useState('0');const [investment,setInvestment]=useState('0');const [limits,setLimits]=useState<Record<string,string>>({});const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 function load(b:Budget){setBudget(b);setIncome(String(b.income_cents/100));setInvestment(String(b.investment_cents/100));setLimits(Object.fromEntries(Object.entries(b.limits).map(([k,v])=>[k,String(v/100)])))}
 useEffect(()=>{let active=true;api<Budget>(`/api/budget?month=${month}&currency=${currency}`).then(b=>active&&load(b)).catch(e=>active&&setError(e.message));return()=>{active=false}},[month,currency,revision]);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('/api/budget',{method:'PUT',body:JSON.stringify({month,currency,income,investment,limits})});onChange('Monthly budget saved. Other months are unchanged.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function copy(){try{if(budget?.previous){const b=await api<Budget>(`/api/budget?month=${budget.previous}&currency=${currency}`);setIncome(String(b.income_cents/100));setInvestment(String(b.investment_cents/100));setLimits(Object.fromEntries(Object.entries(b.limits).map(([k,v])=>[k,String(v/100)])))}}catch(e){setError((e as Error).message)}}
 const allocated=Object.values(limits).reduce((a,b)=>a+Number(b||0),0)*100;const available=Number(income||0)*100-allocated-Number(investment||0)*100;
 return <form onSubmit={save}><div className="panel budget-heading"><div><span className="eyebrow">PLAN WITH INTENTION</span><h2>Your monthly allocation</h2><p className="muted">A plan for {month} in {currency}. Your planned income is separate from money actually received.</p></div>{budget?.previous&&<button type="button" className="secondary" onClick={()=>void copy()}>Copy plan from {budget.previous}</button>}<div className="form-grid"><label>Planned income<input type="number" step="0.01" min="0" required value={income} onChange={e=>setIncome(e.target.value)}/></label><label>Investment target<input type="number" step="0.01" min="0" required value={investment} onChange={e=>setInvestment(e.target.value)}/></label></div><div className="budget-summary"><span>Category limits <b>{money(allocated,currency)}</b></span><span>Unallocated <b className={available<0?'negative':'positive'}>{money(available,currency)}</b></span><span>Income received <b>{money(dashboard.totals.income,currency)}</b></span></div></div>
  <section className="panel"><div className="panel-heading"><div><span className="eyebrow">PLAN VS. REALITY</span><h2>Category budgets</h2></div><span className="muted">Approved spending · refunds deducted</span></div><p className="muted">Each limit covers transactions assigned directly to that category. Subcategories have their own limits, so allocations are never counted twice.</p><div className="budget-rows">{settings.categories.map(c=>{const actual=dashboard.direct_categories[String(c.id)]||0;const limit=Number(limits[c.id]||0)*100;return <div className="budget-row" key={c.id}><div><strong><i style={{background:c.color}}/>{c.parent_id?`${settings.categories.find(p=>p.id===c.parent_id)?.name} / `:''}{c.name}</strong><div className="track"><span style={{width:`${limit?Math.min(100,Math.max(0,actual)/limit*100):0}%`,background:actual>limit&&limit>0?'#ad6759':c.color}}/></div></div><label>Limit<input aria-label={`${c.name} budget limit`} type="number" min="0" step="0.01" value={limits[c.id]||''} placeholder="0.00" onChange={e=>setLimits({...limits,[c.id]:e.target.value})}/></label><span><small>Spent</small>{money(actual,currency)}</span><span className={actual>limit&&limit>0?'negative':''}><small>Remaining</small>{limit?money(limit-actual,currency):'No limit'}</span></div>})}</div></section>{error&&<p role="alert" className="error-text">{error}</p>}<div className="page-actions"><button className="primary" disabled={busy}>{busy?'Saving…':'Save monthly budget'}<Check size={16}/></button></div></form>
}

function Categories({settings,onChange}:{settings:Settings;onChange:(s:string)=>void}){
 const [edit,setEdit]=useState<Category|null>(null);const [name,setName]=useState('');const [parent,setParent]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await api(edit?`/api/categories/${edit.id}`:'/api/categories',{method:edit?'PUT':'POST',body:JSON.stringify({name,parent_id:parent?Number(parent):null})});setEdit(null);setName('');setParent('');onChange('Categories updated.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="categories-layout"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">YOUR STRUCTURE</span><h2>Categories & subcategories</h2></div><span className="subtle-tag">{settings.categories.length}</span></div><div className="category-list">{settings.categories.map(c=><button key={c.id} onClick={()=>{setEdit(c);setName(c.name);setParent(c.parent_id?.toString()||'')}}><span><i style={{background:c.color}}/>{c.parent_id&&<small>{settings.categories.find(p=>p.id===c.parent_id)?.name} / </small>}{c.name}</span><ChevronRight size={15}/></button>)}</div></section><form className="panel" onSubmit={save}><span className="eyebrow">MAKE IT YOURS</span><h2>{edit?'Edit category':'Add a category'}</h2><p className="muted">Use categories for spending totals and labels for extra context, such as a particular trip.</p><label>Name<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><label>Parent category<select value={parent} onChange={e=>setParent(e.target.value)}><option value="">Top level</option>{settings.categories.filter(c=>c.id!==edit?.id).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{error&&<p role="alert" className="error-text">{error}</p>}<div className="page-actions">{edit&&<button className="text-button" type="button" onClick={()=>{setEdit(null);setName('');setParent('')}}>Cancel edit</button>}<button className="primary" disabled={busy}>{busy?'Saving…':edit?'Save changes':'Add category'}</button></div></form></div>
}

function SettingsPage({settings,revision,onAccount}:{settings:Settings;revision:number;onAccount:()=>void}){
 const [history,setHistory]=useState<{batches:{id:number;account:string;filename:string;imported:number;duplicates:number;start:string;end:string;coverage_confirmed:boolean}[];gaps:{account:string;start:string;end:string}[]}>({batches:[],gaps:[]});const [error,setError]=useState('');
 useEffect(()=>{api<typeof history>('/api/imports').then(setHistory).catch(e=>setError(e.message))},[revision]);
 return <><InstallApp/><section className="panel"><div className="panel-heading"><div><span className="eyebrow">CONNECTED BY YOU</span><h2>Your accounts</h2></div><button className="secondary" onClick={onAccount}><Plus size={16}/>Add account</button></div><div className="account-grid">{settings.accounts.map(a=><article key={a.id}><Landmark size={23}/><strong>{a.name}</strong><span>{a.bank||'Bank account'} · {a.currency}</span></article>)}</div><p className="muted">These are statement import folders, not live bank connections. Account balances are not inferred from partial statements.</p></section>
  <section className="panel"><div className="panel-heading"><div><span className="eyebrow">YOUR DATA, YOUR COPY</span><h2>Export & backup</h2></div><ShieldCheck size={24}/></div><p>{settings.hosted?'Your data is stored on your private hosting service.':'The database is stored in this project’s OneDrive folder and may sync according to your OneDrive settings.'} Create a database backup to preserve accounts, transactions, budgets, and import history.</p><div className="page-actions"><a className="button secondary" href="/api/export" download><FileSpreadsheet size={16}/>Export transactions CSV</a><a className="button primary" href="/api/backup" download><Download size={16}/>Download database backup</a></div></section>
  {settings.migration&&<section className="panel migration"><span className="eyebrow">CONTINUITY MATTERS</span><h2>Your original Budget LPC records</h2><p>{Object.entries(settings.migration.imported).map(([k,v])=>`${v} ${k.toLowerCase()}`).join(' · ')} copied to this version. {settings.migration.reconciled?'Imported monthly totals were reconciled.':''} The original database and a full backup are preserved.</p>{settings.migration.legacy_savings_overrides.length>0&&<p className="muted">{settings.migration.legacy_savings_overrides.length} old manual savings override(s) remain in the backup. Savings here are calculated from transactions, so cards and charts agree.</p>}{settings.migration.issues.length>0&&<details><summary>{settings.migration.issues.length} original rows need attention</summary><ul>{settings.migration.issues.map((issue,i)=><li key={i}>{issue.sheet}, row {issue.row}: {issue.reason}</li>)}</ul></details>}</section>}
  <section className="panel"><div className="panel-heading"><div><span className="eyebrow">STATEMENT TRAIL</span><h2>Import history</h2></div></div>{error&&<p role="alert">{error}</p>}{history.gaps.map((g,i)=><p className="notice" key={i}>{g.account}: missing confirmed coverage between {g.start} and {g.end}.</p>)}{history.batches.length?<div className="table-scroll"><table><thead><tr><th>Statement / account</th><th>Period</th><th>Imported</th><th>Duplicates</th></tr></thead><tbody>{history.batches.map(b=><tr key={b.id}><td><strong>{b.filename}</strong><small>{b.account}</small></td><td>{b.start} → {b.end}<small>{b.coverage_confirmed?'Statement coverage confirmed':'Transaction dates only'}</small></td><td>{b.imported}</td><td>{b.duplicates}</td></tr>)}</tbody></table></div>:<p className="empty-small">No bank statements imported yet.</p>}</section>
  <section className="panel"><h2>Supported statement files</h2><p>Excel .xlsx, delimited CSV, and HTML bank exports saved as .xls. The preview lets you select date, description, signed amount or debit/credit columns, and currency. Actual ING, CaixaBank, ADCB, Revolut and Seychelles exports still need verification with your files.</p><p className="muted">Supported currencies: {settings.currencies.join(', ')}. Totals remain separate; there is no automatic conversion. Imports work without AI. Optional Codex suggestions require a separate CLI sign-in and explicit permission in Review.</p></section>
 </>
}

