import { useEffect, useState } from 'react';
import { Check, Link, Pencil, Search, Sparkles, X, RotateCcw } from 'lucide-react';
import {api,money,type Settings,type Transaction} from './types';

type Props={settings:Settings;month:string;currency:string;view:string;revision:number;onChange:(message:string)=>void;onEdit:(row:Transaction)=>void};
export default function Ledger({settings,month,currency,view,revision,onChange,onEdit}:Props){
 const [rows,setRows]=useState<Transaction[]>([]);const [error,setError]=useState('');const [search,setSearch]=useState('');const [allDates,setAllDates]=useState(view==='Review');const [status,setStatus]=useState('');const [kind,setKind]=useState('');const [category,setCategory]=useState('');const [loading,setLoading]=useState(true);const [selected,setSelected]=useState<number[]>([]);const [bulkCategory,setBulkCategory]=useState('');const [bulkKind,setBulkKind]=useState('');const [bulkBusy,setBulkBusy]=useState(false);const [aiConsent,setAiConsent]=useState(false);const [aiBusy,setAiBusy]=useState(false);
 useEffect(()=>{let active=true;setLoading(true);const p=new URLSearchParams({currency,search,month:allDates?'':month,status:view==='Review'?'pending':status,kind:view==='Income'?'income':view==='Investments'?'investment':kind,category_id:category});if(!category)p.delete('category_id');
  api<Transaction[]>('/api/transactions?'+p).then(data=>{if(active){setRows(data);setSelected([]);setError('')}}).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false}
 },[month,currency,view,revision,search,allDates,status,kind,category]);
 async function suggest(){setAiBusy(true);setError('');try{const ids=rows.filter(r=>['expense','refund'].includes(r.kind)).slice(0,10).map(r=>r.id);const result=await api<{suggested:number}>('/api/review/suggest',{method:'POST',body:JSON.stringify({ids,consent:true})});onChange(`${result.suggested} suggestions are ready. Review before approving.`)}catch(e){setError((e as Error).message)}finally{setAiBusy(false)}}
 async function bulkApprove(){setBulkBusy(true);setError('');try{const answer=await api<{approved:number}>('/api/review/approve-batch',{method:'POST',body:JSON.stringify({ids:selected,category_id:bulkCategory?Number(bulkCategory):null,kind:bulkKind||null})});onChange(`${answer.approved} transactions approved.`)}catch(e){setError((e as Error).message)}finally{setBulkBusy(false)}}
 return <>
  <div className="section-toolbar"><label className="search"><Search size={17}/><input aria-label="Search transactions" placeholder="Search description, category or label" value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="check"><input type="checkbox" checked={allDates} onChange={e=>setAllDates(e.target.checked)}/>All dates</label>
   {view!=='Review'&&<select aria-label="Transaction status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="approved">Approved</option><option value="pending">Pending</option><option value="excluded">Excluded</option><option value="matched">Matched bank rows</option></select>}
   {view==='Transactions'&&<select aria-label="Transaction type" value={kind} onChange={e=>setKind(e.target.value)}><option value="">All types</option>{['income','expense','refund','transfer','investment'].map(k=><option key={k}>{k}</option>)}</select>}
   <select aria-label="Category filter" value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{settings.categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select>
  </div>
  {view==='Review'&&<div className="review-intro"><div><h3>Your final say on every transaction.</h3><p>Confirm the type and category. Incoming money may be income, a refund, or a transfer. Match existing entries when prompted to avoid counting twice.</p></div><details><summary><Sparkles size={15}/>Optional AI suggestions</summary><p>Send descriptions, amounts, currencies and category names for up to 10 visible expenses/refunds to Codex. Merchant research may use web search. A Codex CLI sign-in is required.</p><label className="check"><input type="checkbox" checked={aiConsent} onChange={e=>setAiConsent(e.target.checked)}/>Allow this batch to be sent to Codex</label><button className="secondary" disabled={!aiConsent||aiBusy||!rows.some(r=>['expense','refund'].includes(r.kind))} onClick={()=>void suggest()}>{aiBusy?'Requesting suggestions…':'Suggest for up to 10 transactions'}</button></details></div>}
  {view==='Review'&&rows.length>0&&<div className="bulk-review"><label className="check"><input type="checkbox" checked={selected.length===Math.min(rows.length,200)} onChange={e=>setSelected(e.target.checked?rows.slice(0,200).map(r=>r.id):[])}/>Select up to 200</label><select aria-label="Batch transaction type" value={bulkKind} onChange={e=>setBulkKind(e.target.value)}><option value="">Keep each suggested type</option>{['income','expense','refund','transfer','investment'].map(k=><option key={k}>{k}</option>)}</select><select aria-label="Batch category" value={bulkCategory} onChange={e=>setBulkCategory(e.target.value)}><option value="">Choose batch category</option>{settings.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="primary small" disabled={!selected.length||bulkBusy} onClick={()=>void bulkApprove()}>{bulkBusy?'Approving…':`Approve selected (${selected.length})`}</button><small>Batch approval uses the type and category above, with a variable expense pattern. Possible manual matches need individual review.</small></div>}
  {error&&<p role="alert" className="notice error">{error}</p>}
  <div className="section-caption"><span>{loading?'Loading…':`${rows.length} transactions`}</span><span>{currency} only · {allDates?'All dates':month}</span></div>
  {!loading&&!rows.length?<div className="empty"><Check size={28}/><h3>{view==='Review'?'Your review queue is clear':'No transactions here yet'}</h3><p>{view==='Review'?'Import a statement to review its transactions.':'Try another month or currency, or add your first entry.'}</p></div>:<div className="ledger-list">{rows.map(row=><TransactionRow key={`${row.id}-${revision}`} row={row} settings={settings} onChange={onChange} onEdit={onEdit} selected={selected.includes(row.id)} onSelect={view==='Review'?()=>setSelected(ids=>ids.includes(row.id)?ids.filter(id=>id!==row.id):[...ids,row.id].slice(0,200)):undefined}/>)}</div>}
 </>
}

function TransactionRow({row,settings,onChange,onEdit,selected,onSelect}:{row:Transaction;settings:Settings;onChange:(message:string)=>void;onEdit:(r:Transaction)=>void;selected:boolean;onSelect?:()=>void}){
 const [expanded,setExpanded]=useState(row.status==='pending');const [kind,setKind]=useState(row.kind);const [category,setCategory]=useState(row.category_id?.toString()||'');const [label,setLabel]=useState(row.label);const [expenseType,setExpenseType]=useState(row.expense_type);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function save(action='approve',match_id:number|null=null){setBusy(true);setError('');try{await api(`/api/transactions/${row.id}/review`,{method:'POST',body:JSON.stringify({kind,category_id:category?Number(category):null,label,expense_type:expenseType,action,match_id})});onChange(action==='unmatch'?'Match undone. The bank row is pending again.':action==='match'?'Matched to your existing entry. Counted once.':action==='exclude'?'Transaction excluded. You can restore it from the excluded filter.':action==='restore'?'Returned to review.':'Transaction approved. Totals updated.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <article className={`transaction-card ${row.status==='pending'?'pending':''}`}>
  <div className="transaction-heading">{onSelect&&<input type="checkbox" aria-label={`Select ${row.description}`} checked={selected} onChange={onSelect}/>}<div className={`transaction-symbol ${row.cents>=0?'positive':''}`}>{row.cents>=0?'↙':'↗'}</div><div className="transaction-description"><strong>{row.description}</strong><span>{row.date} · {row.account} {row.label&&`· ${row.label}`}</span></div><span className={`badge ${row.status==='pending'?'amber':row.status==='excluded'?'neutral':'green'}`}>{row.status==='approved'?row.kind:row.status}</span><strong className={`transaction-amount ${row.cents>=0?'positive':''}`}>{money(row.cents,row.currency)}</strong><button className="icon-button" aria-label={`Edit ${row.description}`} onClick={()=>{if(row.source!=='bank'&&row.status==='approved')onEdit(row);else setExpanded(!expanded)}}><Pencil size={16}/></button></div>
  {row.category&&!expanded&&<p className="transaction-category">{row.category} · {row.expense_type}</p>}
  {expanded&&row.status==='matched'&&<div className="transaction-details"><p className="muted">This bank movement is linked to an existing manual record and is counted only once.</p><button disabled={busy} className="secondary" onClick={()=>void save('unmatch')}><RotateCcw size={15}/>Undo match</button>{error&&<p role="alert" className="error-text">{error}</p>}</div>}
  {expanded&&row.status!=='matched'&&<div className="transaction-details">
   {row.suggestion&&<div className="suggestion"><Sparkles size={15}/><span>{row.suggestion.description} · Suggested: {row.suggestion.category} ({Math.round(row.suggestion.confidence*100)}%)</span><button className="text-button" onClick={()=>setCategory(String(settings.categories.find(c=>c.name===row.suggestion?.category)?.id||''))}>Use category</button></div>}
   {row.matches?.length>0&&<div className="match-notice"><Link size={17}/><div><strong>Possible existing entry</strong>{row.matches.map(m=><div key={m.id}><span>{m.date} · {m.description}</span><button disabled={busy} className="text-button" onClick={()=>void save('match',m.id)}>Match — count once</button></div>)}</div></div>}
   <div className="review-fields"><label>Type<select value={kind} onChange={e=>setKind(e.target.value)}>{(row.cents>=0?['income','refund','transfer']:['expense','investment','transfer']).map(k=><option key={k}>{k}</option>)}</select></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Choose a category</option>{settings.categories.map(c=><option key={c.id} value={c.id}>{c.parent_id?`${settings.categories.find(p=>p.id===c.parent_id)?.name} / `:''}{c.name}</option>)}</select></label><label>Fixed or variable<select value={expenseType} onChange={e=>setExpenseType(e.target.value)}><option value="variable">Variable</option><option value="fixed">Fixed</option></select></label><label>Label (optional)<input maxLength={80} value={label} placeholder="e.g. Summer trip" onChange={e=>setLabel(e.target.value)}/></label></div>
   {error&&<p role="alert" className="error-text">{error}</p>}
   <div className="review-actions"><span className="muted">{row.source==='bank'?'Original bank date and amount are preserved.':'Your manual entry.'}</span>{row.status==='excluded'?<button className="secondary" disabled={busy} onClick={()=>void save('restore')}><RotateCcw size={15}/>Restore to review</button>:<><button className="text-button" disabled={busy} onClick={()=>void save('exclude')}><X size={15}/>Exclude</button><button className="primary small" disabled={busy} onClick={()=>void save()}><Check size={15}/>{busy?'Saving…':'Approve'}</button></>}</div>
  </div>}
 </article>
}

